language: go
sudo: false

go:
  - "1.7.x"
  - "1.8.x"
  - "1.9"
  - "1.10"
  - "tip"

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./vimeo

after_success:
  - bash <(curl -s https://codecov.io/bash)
