language: go
sudo: false

go:
  - 1.6.3
  - 1.7
  - 1.8
  - 1.9
  - 1.10
  - tip

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./vimeo

after_success:
  - bash <(curl -s https://codecov.io/bash)
